name: CI/CD Pipeline
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@2
        with:
          apiToken: ${{ secrets.CF_ANALYTICS_WORKER_TOKEN }}
          workingDirectory: ./
